baseURL = "https://selindevin.github.io/selinsstuff/"
languageCode = "en-us"
title = "Selin's Website"
theme = "hugo-book"
author = "Selin"
defaultContentLanguage = "en"
disableLanguages = true

[[menu.main]]
name = "About Me"
url = "/about/"
weight = 2